<?php

namespace KikiceBundle\Repository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends \Doctrine\ORM\EntityRepository
{
}
